<a href="https://colab.research.google.com/github/Maviya5/CE888/blob/master/Lab5/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [91]:
df = pd.read_csv('jester-data-1.csv', header=None)
print(df)


       0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]


In [92]:
df=df.drop(df.columns[0],1)
print(df)

         1      2      3      4     5    ...    96     97     98     99     100
0      -7.82   8.79  -9.66  -8.16 -7.52  ...  99.00  -5.63  99.00  99.00  99.00
1       4.08  -0.29   6.36   4.37 -2.38  ...  -2.14   3.06   0.34  -4.32   1.07
2      99.00  99.00  99.00  99.00  9.03  ...  99.00  99.00  99.00  99.00  99.00
3      99.00   8.35  99.00  99.00  1.80  ...  99.00  99.00  99.00  99.00  99.00
4       8.50   4.61  -4.17  -5.39  1.36  ...   1.55   3.11   6.55   1.80   1.60
...      ...    ...    ...    ...   ...  ...    ...    ...    ...    ...    ...
24978   0.44   7.43   9.08   2.33  3.20  ...   9.03   6.55   8.69   8.79   7.43
24979   9.13  -8.16   8.59   9.08  0.87  ...  -8.20  -7.23  -8.59   9.13   8.45
24980  99.00  99.00  99.00  99.00 -7.77  ...  99.00  99.00  99.00  99.00  99.00
24981  99.00  99.00  99.00  99.00 -9.71  ...  99.00  99.00  99.00  99.00  99.00
24982   2.43   2.67  -3.98   4.27 -2.28  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 100 columns]


In [93]:
arr = df.values
print(arr.shape)

(24983, 100)


In [94]:

rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

1810455 (1810455,)


In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:
new_arr, idx = replace(arr, 0.1)

In [97]:
arr[idx[0][0], idx[1][0]]


6.21

In [98]:
new_arr[idx[0][0], idx[1][0]]


99.0

In [0]:
n_latent_factors =15

user_ratings = df.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [119]:
latent_item_features


array([[0.512, 0.208, 0.44 , ..., 0.125, 0.572, 0.343],
       [0.211, 0.072, 0.604, ..., 0.574, 0.141, 0.32 ],
       [0.102, 0.683, 0.831, ..., 0.991, 0.953, 0.813],
       ...,
       [0.43 , 0.483, 0.922, ..., 0.064, 0.202, 0.744],
       [0.749, 0.09 , 0.271, ..., 0.706, 0.269, 0.072],
       [0.66 , 0.311, 0.111, ..., 0.976, 0.036, 0.838]])

In [120]:
latent_user_preferences


array([[0.39 , 0.06 , 0.948, ..., 0.274, 0.829, 0.323],
       [0.896, 0.487, 0.224, ..., 0.322, 0.631, 0.129],
       [0.595, 0.086, 0.537, ..., 0.35 , 0.396, 0.139],
       ...,
       [0.88 , 0.397, 0.18 , ..., 0.363, 0.399, 0.907],
       [0.623, 0.353, 0.661, ..., 0.309, 0.871, 0.108],
       [0.75 , 0.19 , 0.583, ..., 0.715, 0.217, 0.092]])

In [0]:

def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=100):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = new_arr[user_id][item_id]
                if (rating!=99):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10) == 0:
          print(mse)

In [122]:
sgd()

25.854170282035643
24.463042946870495
20.224491963001743
17.893981969366582
17.531013308101404
17.042945507690497
16.36505617368004
15.709076644468505
15.15323289648833
14.68202136887113


In [123]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[-4.013, -2.502, -6.958, ..., -2.139, -7.32 , -3.521],
       [ 4.495,  2.742,  6.964, ...,  3.064,  2.346,  5.646],
       [ 6.914,  5.629,  8.172, ...,  5.404,  6.802,  6.617],
       ...,
       [-4.4  , -3.221, -2.535, ...,  2.19 ,  0.924,  2.188],
       [ 0.972,  0.622, -0.612, ..., -1.799, -4.649, -1.481],
       [ 3.29 ,  3.836,  1.719, ...,  5.227,  4.101,  4.944]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [125]:
comparison_data

1    ...                          100
0      (-7.82, -4.012769173470528)  ...    (99.0, -3.52128156707402)
1        (4.08, 4.494637100343435)  ...   (1.07, 5.6459426622234306)
2         (99.0, 6.91352186482363)  ...    (99.0, 6.616540851981073)
3        (99.0, 3.330108813616702)  ...   (99.0, 3.9654156243659733)
4        (8.5, 3.3342545714655296)  ...      (1.6, 6.03663000980526)
...                            ...  ...                          ...
24978   (0.44, 1.0259327852318916)  ...   (7.43, 7.2093291073069246)
24979    (9.13, 7.418664175043928)  ...   (8.45, 1.3639029160014116)
24980   (99.0, -4.400352900435062)  ...   (99.0, 2.1879426080639344)
24981    (99.0, 0.971807187835594)  ...  (99.0, -1.4812912689193316)
24982   (2.43, 3.2904157367977884)  ...    (99.0, 4.944410757170807)

[24983 rows x 100 columns]